Sensirion/embedded-common

- hw_i2c/sample-implementations/linux_user_space/sensirion_hw_i2c_implementation.c
Support communication with any i2c device on the bus. Previously
the device address was set on initialization and was only checked
on each read/write. The code can now rebind the i2c address.
> Multi-address i2c communication

- hw_i2c/sample-implementations/mbed/sgp30_example_usage.cpp
we do not scale ethanol and h2 signals anymore to avoid unnecessary
computation
> Drop signal scaling for SGP

- hw_i2c/sensirion_hw_i2c_implementation.c
- sensirion_arch_config.h
- sensirion_common.h
- sw_i2c/sensirion_sw_i2c.c
- sw_i2c/sensirion_sw_i2c_implementation.c
* Document precision req. of sensirion_sleep_usec()
* Fix endianness issues when BIG_ENDIAN is defined
> Endianness and timer improvements

- sw_i2c/sample-implementations/linux_user_space/sensirion_sw_i2c_implementation.c
- sw_i2c/sensirion_sw_i2c.c
* Fix an issue where the last master-read byte was ACK'ed instead of NACK'ed
* Support i2c clock stretching (master hold)
* Provide a generic implementation for sw-i2c using Linux's gpio subsystem (`/sys/class/gpio`)
> i2c Clock Stretching, generic Linux GPIO impl, Fix

- sensirion_common.c
- sensirion_common.h
Let word-commands return words in host/system-endianness
Previously the returned words were big-endian causing confusion
between writes that took system-endian values and reads that returned
big-endian values.
Adds sensirion_i2c_read_bytes that returns the (crc-checked) byte stream as
received.
Provide SENSIRION_WORDS_TO_BYES(word_array, num_wods) to convert a
word array back to a bytes array (in the order the bytes arrive on the
wire, i.e. big-endian).
> Host-Endian Words

- sw_i2c/sensirion_sw_i2c.c
The error return value is actually signed. This is not a breaking change, since it only changes internal functions. So no change to the public API.
> Fix sign conversion warnings

- AUTHORS
- sw_i2c/sample-implementations/linux_user_space/sensirion_sw_i2c_implementation.c
The I2C software sample implementation generated two warnings of type
`sign-conversion` and `sign-compare`. This commit fixes these warnings.
> Fix warnings in linux I2C SW sample implementation

- hw_i2c/sensirion_hw_i2c_implementation.c
There were cases were people were using the I2C dummy implementation by accident and didn't notice directly, since all I2C calls succeeded.
> Return errors in I2C dummy implementation

- sensirion_common.c
- sensirion_common.h
Rename sensirion_i2c_read_bytes to sensirion_i2c_read_words_as_bytes
to hint that the size parameter is in words and not in bytes.
> Rename sensirion_i2c_read_bytes to avoid confusion

- sensirion_arch_config.h
It isn't used anywhere and float is defined to be a single precision
floating point type and on almost all platforms it is a IEEE-754 32 bit
floating point.
> arch_config: Remove float32_t typedef

- sensirion_common.c
- sensirion_common.h
This MR adds and uses new config independent endianness conversion functions
Currently, driver users need to specify whether the use a big or little endian system by defining SENSIRION_BIG_ENDIAN (in sensirion_arch_config.h), this MR initiates the switch over
to using configuration independent functions that use the raw byte strings.
The old conversion functions *_to_cpu (e.g. be16_to_cpu) remain in place for now but should be considered deprecated.
The MR also contains a small Docstring fix I slipped in
> Config independent endianness conversion

- hw_i2c/sample-implementations/mbed/sgp30_example_usage.cpp
- sensirion_common.c
- sensirion_common.h
- sw_i2c/sensirion_sw_i2c.c
We use error codes for error handling and drivers define their error
using FOO_ERROR, so using that in the naming is more consistent.
> Add NO_ERROR define and deprecate STATUS_OK

- hw_i2c/sample-implementations/mbed/sensirion_hw_i2c_implementation.cpp
MBED boards define constants for the I2C SDA/SCL pins. I'd propose to make this the default (see https://os.mbed.com/docs/mbed-os/v5.15/feature-i2c-doxy/classmbed_1_1_i2_c.html)
Note that I did not update the SW implementation, as I would expect that SW I2C is usually used on non-standard pins
> Use 'I2C_{SDA,SCL}' constants as default pins

- sensirion_common.c
- sensirion_common.h
The latest version of embedded-common utilities added conversion functions `sensirion_bytes_to_uint32_t` and `sensirion_bytes_to_float`. There seems to have been a copy-paste error resulting in the `sensirion_bytes_to_float` returning `uint32_t` instead, quietly rounding down the reading values.
I have tested the change with an SCD30 driven over hardware I²C by a Raspberry Pi 4 (BCM2711) compiled with GCC and it appears to work fine. The values returned are no longer rounded down and agree with those reported by a nearby BME680 (temperature & relative humidity) within a small margin of error.
> Fix byte-to-float conversion issue

- README.md
We removed the typedef in https://github.com/Sensirion/embedded-common/pull/38
> Remove float32_t typdef from README

- sensirion_arch_config.h
- sensirion_common.h
All drivers are migrated or in the process of being migrated, so we can remove these for the next version and avoid confusing users with it.
> Remove legacy endianness conversion macros

- hw_i2c/sample-implementations/zephyr_user_space/sensirion_hw_i2c_implementation.c
Porting the SPS30 driver to Zephyr User-Space (https://github.com/zephyrproject-rtos/zephyr). Tested with nRF9160 and STM32L4.
> Add Zephyr User-Space sample implementation

- README.md
- test-config/base_config.inc
- test-config/sensirion_test_setup.cpp
- test-config/sensirion_test_setup.h
In an effort to move tests to be with the driver repo and not on there
own, the general configuration files for this setup are with the
embedded common repo. Add those configuration files.
> Add general configuration for tests

- hw_i2c/sample-implementations/zephyr_user_space/sensirion_hw_i2c_implementation.c
Both k_usleep / usleep provide the same functionality, but "usleep" requires the support of POSIX to be enabled in the zephyr build, which increases the image size. As the same functionality can be achieved by using the native "k_usleep" without additional memory usage, it should be preferred over "usleep".
> Use Zephyr Native k_usleep instead of POSIX usleep

- sensirion_common.c
- sensirion_common.h
Add function sensirion_bytes_to_uint16_t since it's needed for the
SEN44 driver and in general a useful addition.
> Add function sensirion_bytes_to_uint16_t

- test-config/sensirion_test_setup.cpp
- test-config/sensirion_test_setup.h
Just use sensirion_i2c_general_call_reset  directly.
> Remove deprecated i2c_reset

- CHANGELOG.md
- shdlc/sensirion_shdlc.c
- shdlc/sensirion_shdlc.h
Fixed the handling of execution errors when using the SHDLC protocol. Now execution errors reported in the state byte result in a error.
> Check if execution of command failed

- i2c/sample-implementations/GPIO_bit_banging/sensirion_i2c_hal.c
Apparently the function names didn't get renamed during some
refactoring.
> Fix the SW I2C / bit banging HAL implementation

- shdlc/sample-implementations/linux_user_space/sensirion_uart_hal.c
- shdlc/sensirion_uart_hal.c
- shdlc/sensirion_uart_hal.h
It isn't really usable and not even implemented in the Linux sample
implementation.
> Remove sensirion_uart_hal_select_port

- CHANGELOG.md
- i2c/sample-implementations/Atmel_SAMD2_series/sensirion_i2c_hal.c
- i2c/sample-implementations/GPIO_bit_banging/sensirion_i2c_hal.c
- i2c/sample-implementations/Nordic_nRF5_series/sensirion_i2c_hal.c
- i2c/sample-implementations/STM32F1_series/sensirion_i2c_hal.c
- i2c/sample-implementations/linux_user_space/sensirion_i2c_hal.c
- i2c/sample-implementations/mbed/sensirion_i2c_hal.cpp
- i2c/sample-implementations/zephyr_user_space/sensirion_i2c_hal.c
- i2c/sensirion_i2c_hal.c
- i2c/sensirion_i2c_hal.h
Change count for Sensirion I2C HAL from uint16_t to unit8_t. We never have a count that requires 16-bit integers, therefore we can safely change it to 8-bit.
This avoids compiler warnings on some platforms.
> Change count to uint8_t
